### PR TITLE
Change helper text

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>
https://github.com/stolostron/backlog/issues/24920

### CODE REVIEW

**Review by fxiang1 — APPROVED** [review]
LGTM!

**Comment by fxiang1** [comment]
@chenz4027 I think the main change should here https://github.com/stolostron/console/blob/main/frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateInfrastructure/CreateControlPlane.tsx#L140

The text that Matt was looking might be outdated :-)

**Comment by chenz4027** [comment]
@fxiang1 Ah thanks! Will make a change in console as well

**Review by fxiang1 — APPROVED** [review]
LGTM!

**Review by jamestalton — APPROVED** [review]
lgtm

**Pull request merged**
