### PR TITLE
add string context for nav buttons and empty state

### PR DESCRIPTION
**Pull request by RobDolares**
related issue: https://issues.redhat.com/browse/ACM-3447

### CODE REVIEW

**Review by KevinFCormier — CHANGES_REQUESTED** [review]
I don't think this approach will work. We shouldn't be assembling strings from multiple translated parts. I think we should remove the `article` prop, as it would only ever be used as a piece of a larger string. Same might be true of `singular` and `plural`... unless we use them on their own somewhere. I would also be wary of any code that changes the capitalization. May not work as expected for other languages.

**Comment by KevinFCormier** [comment]
> I don't think this approach will work. We shouldn't be assembling strings from multiple translated parts. I think we should remove the `article` prop, as it would only ever be used as a piece of a larger string. Same might be true of `singular` and `plural`... unless we use them on their own somewhere. I would also be wary of any code that changes the capitalization. May not work as expected for other languages.

The back and cancel parts are good, though.

The main changes I think would be to make `noItemsString` and `createItemString` just strings. The user supplies the `article` and `plural` props, so they don't need them passed back into a function.

And then as I mentioned, removing the string props (and/or moving them into your string context instead, so all the strings are defined in one place).

**Review by KevinFCormier — APPROVED** [review]

**Review by Randy424 — APPROVED** [review]

**Review by chenz4027 — APPROVED** [review]
/lgtm
/approved

**Pull request merged**
